## Practice
1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [1]:
#1
import numpy as np
x=np.zeros((8,8))
y=np.full((8,1),1)
z=np.full((1,10),1)
a=np.hstack([y,x])
b=np.hstack([a,y])
c=np.vstack([z,b])
np.vstack([c,z])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [2]:
#2
a=np.arange(5)
np.tile(a,(5,1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [3]:
#3
a=np.array([[0,1],[1,0]])
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [4]:
#4
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix 

In [5]:
#5
a=np.random.randn(5,5)
ave=a.mean()
std=a.std()
a=(a-ave)/std
a

array([[-0.11383212,  0.81596561, -0.38785435, -2.50347193,  0.93148161],
       [ 1.53539723, -0.22070965, -0.04727404, -0.87326555, -0.12540429],
       [ 0.00673141, -0.00481414, -0.12480447,  0.20558722, -0.14309175],
       [-2.79432092,  0.03088972,  0.8679157 , -0.00431867,  1.16358879],
       [ 1.14373292,  1.46738858,  0.01576882, -0.5598944 , -0.2813913 ]])

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [6]:
#6
import math
cart=np.random.randn(10,2)
R=[]
T=[]
print("X,Y:")
print(cart[:,0],cart[:,1])
for i in range(10):
       R.append(math.sqrt(cart[i,0]**2+cart[i,1]**2))
       T.append(math.acos(cart[i,0]/R[i]))
print("R:",R)
print("T:",T)      

X,Y:
[ 2.5212549   0.6811165   1.52800435  0.51752941 -0.73672075  0.0378015
  1.05098486  0.06397325 -0.9551212  -0.15684196] [ 0.28958708  0.82588146  0.46864789  0.1177503  -0.32357592  0.21859514
  0.20300692  2.1759592   1.25923237  1.61831952]
R: [2.537831153552107, 1.0705138309159454, 1.5982578467578437, 0.5307558964465702, 0.8046482672317944, 0.22183955930153046, 1.0704115925737143, 2.176899409007574, 1.5804817834356892, 1.6259020512759619]
T: [0.114357186573936, 0.881166120331399, 0.2975975467558962, 0.22371541080136903, 2.7277469231501685, 1.3995605529281185, 0.1908088666632326, 1.5414047715605435, 2.219711975890808, 1.667411143764751]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [7]:
#7
v=np.array([1,2,3,4,5])
v=np.insert(v,1,[0,0,0])
v=np.insert(v,5,[0,0,0])
v=np.insert(v,9,[0,0,0])
v=np.insert(v,13,[0,0,0])
v
#v[::4] = np.arange(1, 6)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [8]:
#8
print(0 * np.nan,

np.nan == np.nan,

np.inf > np.nan,

np.nan - np.nan,

np.nan in set([np.nan]),

0.3 == 3 * 0.1) 


nan False False nan True False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [9]:
#9
np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)

C:\Users\谢嘉楠\AppData\Local\Temp\ipykernel_49752\822494583.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\谢嘉楠\AppData\Local\Temp\ipykernel_49752\822494583.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\谢嘉楠\AppData\Local\Temp\ipykernel_49752\822494583.py:6: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])